idf_component_register(SRCS "ultra_remote.c"
                    INCLUDE_DIRS "")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $ENV{OPTS_}")

message("-------------------------------------------------------------vvv-------------------------------------------------------------")
message("${CMAKE_C_FLAGS}")
message("-------------------------------------------------------------^^^-------------------------------------------------------------")

